Take data from API
awesome-academy/spoon_master pull request #6
Opened 2020-06-10 10:31 UTC by nmngn

## Related Tickets

- [#Ticket ID](https://dev.framgia.com/redmine/issues/???)
https://edu-redmine.sun-asterisk.vn/issues/24315

## What's this PR do ?

- [ ] Take data from API

## Library
*(List gem, library third party add new)

## Impacted Areas in Application
*(List features, api, models or services that this PR will affect)*

- foo/bar
- bar/baz

## Checklist

- [ ] It was tested in local success ?
- [ ] Fill link PR into ticket and the opposite
- [ ] Note reason, scope of influence, solution into ticket
- [ ] Validate UI/Model/API

## screenshot (optional)

## Notes
*(Other notes)*

2020-06-13 01:44 UTC, datdt-1935 commented on .swiftlint.yml
> +- mark
sao lại disable force_cast?

2020-06-13 01:44 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
```suggestion
    @IBOutlet private weak var tableView: UITableView!
```

2020-06-13 01:44 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        self.tableView.register(UINib(nibName: "HomeTableViewCell", bundle: nil), forCellReuseIdentifier: "HomeTableViewCell")
dùng lib Then

2020-06-13 01:44 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +    }}
sai indent

2020-06-13 01:44 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        }
để 0, 1 ra constant cho rõ nghĩa
không access trực tiếp vào view trong cell, tạo 1 hàm configCell để set dữ liệu

2020-06-13 01:44 UTC, datdt-1935 commented on Spoon Master/Repositories/Repositories.swift
> +
sao lại dùng static?
Ở đây đang chưa đúng mô hình

2020-06-13 01:44 UTC, datdt-1935 commented on Spoon Master/Scenes/Main/HomeTableViewCell/HomeTableViewCell.swift
> +    @IBOutlet weak var imageOfFood: UIImageView!
để private

2020-06-13 01:44 UTC, datdt-1935 commented on Spoon Master/Utils/ApiKey.swift
> +}
không đẩy file này lên git

2020-06-13 01:44 UTC, datdt-1935 commented on Spoon Master/Utils/Constant.swift
> +struct K {
sao lại đặt tên như này?

2020-06-13 10:12 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        return 3
để ra Constant

2020-06-13 10:12 UTC, datdt-1935 commented on Spoon Master/Repositories/Repositories.swift
> +            completion(response)
xem lại mô hình MVC mẫu đi, vẫn đang chưa đúng đâu

2020-06-13 10:12 UTC, datdt-1935 commented on Spoon Master/Scenes/Main/HomeTableViewCell/HomeTableViewCell.swift
> +    @IBOutlet weak var categoryTitle: UILabel!
private

2020-06-15 02:44 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +    let repositories = Repositories(api: .share)
private

2020-06-15 02:44 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +    @IBOutlet private weak var tableView: UITableView!
để Outlet lên trên thuộc tính

2020-06-15 02:44 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        tableView.then {
```suggestion
        tableView.do {
```

2020-06-15 02:44 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(withIdentifier: "HomeTableViewCell", for: indexPath) as? HomeTableViewCell else { print("ERROR")
ở trên dùng Constant cho Identifier rồi thì dùng nốt dưới này đi em

2020-06-15 02:44 UTC, datdt-1935 commented on Spoon Master/Data/Source/ApiService.swift
> +                print(response)
bỏ đoạn print debug này đi em

2020-06-15 02:44 UTC, datdt-1935 commented on Spoon Master/Repositories/Repositories.swift
> +class Repositories: UserRepository {
```suggestion
struct RecipeRepository: RecipeRepositoryType {
```

2020-06-15 02:44 UTC, datdt-1935 commented on Spoon Master/Repositories/Repositories.swift
> +            let request = Alamofire.request(input.url)
trong ApiService đã request rồi sao ở đây còn request nữa vậy?

2020-06-15 02:44 UTC, datdt-1935 commented on Spoon Master/Utils/ApiKey.swift
> +}
vẫn chưa remove khỏi git file này à?

2020-06-15 02:44 UTC, datdt-1935 commented on Spoon Master/Utils/URLs.swift
> +    static let randomRecipes = "https://api.spoonacular.com/recipes/random?apiKey="
để param cho Request xử lý

2020-06-16 02:16 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        return CGFloat(Constant.heightForRow)
để luôn kiểu là CGFloat ở constant đi em

2020-06-16 02:16 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        return 1
để ra constant

2020-06-16 02:16 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        return 45
tương tự

2020-06-16 02:16 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        return view
để ra 1 file header riêng

2020-06-16 02:16 UTC, datdt-1935 commented on Spoon Master/Data/Source/API/SearchRequest.swift
> +    required init?(query: String, number: Int, keyWord: String, apiKey: String) {
Không cần đẩy apiKey làm param

2020-06-16 02:16 UTC, datdt-1935 commented on Spoon Master/Repositories/Repositories.swift
> +    func takeRandomRecipesData(keyWord: String, apiKey: String, completion: @escaping (BaseResult<RandomRecipes>) -> Void )
```suggestion
    func takeRandomRecipesData(keyWord: String, completion: @escaping (BaseResult<RandomRecipes>) -> Void )
```

2020-06-16 02:16 UTC, datdt-1935 commented on Spoon Master/Repositories/Repositories.swift
> +        api?.request(input: input!, completion: { (object: RandomRecipes?, error) in
không force unwrap

2020-06-16 02:16 UTC, datdt-1935 commented on Spoon Master/Repositories/Repositories.swift
> +    }
```suggestion
    let api: ApiService?
```

2020-06-17 03:01 UTC, anhnv-0990 commented on Spoon Master/Controller/HomeViewController.swift
> +        }
bỏ print đi

2020-06-17 03:03 UTC, anhnv-0990 commented on Spoon Master/Controller/HomeViewController.swift
> +        return Constant.numberOfRowsInSection
trả về count của 1 array chứ

2020-06-17 03:03 UTC, anhnv-0990 commented on Spoon Master/Controller/HomeViewController.swift
> +        var title: String!
k cần !

2020-06-17 03:04 UTC, anhnv-0990 commented on Spoon Master/Controller/HomeViewController.swift
> +        }
dùng switch case

2020-06-17 03:05 UTC, anhnv-0990 commented on Spoon Master/Data/Model/RandomRecipes/AnalyzedInstruction/Step/Step.swift
>      mutating func mapping(map: Map) {
tách ra làm 1 file riêng đi, đừng để chung

2020-06-17 03:14 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +            return UITableViewCell() }
break line và format code

2020-06-17 03:14 UTC, datdt-1935 commented on Spoon Master/Controller/HomeViewController.swift
> +        header.category.text = title
không access view như này

2020-06-17 03:14 UTC, datdt-1935 commented on Spoon Master/Data/Source/API/SearchRequest.swift
> +    super.init(url: URLs.product, requestType: .get, body: body)
sao url ở đây lại khác so với những init còn lại vậy?

2020-06-17 03:14 UTC, datdt-1935 commented on Spoon Master/Data/Source/ApiService.swift
> +        configuration.timeoutIntervalForResource = 30
dùng `then`

2020-06-17 03:14 UTC, datdt-1935 commented on Spoon Master/Scenes/Main/HeaderCell/HomeHeaderView.swift
> +    @IBOutlet weak var category: UILabel!
```suggestion
    @IBOutlet private weak var category: UILabel!
```

2020-06-17 03:14 UTC, datdt-1935 commented on Spoon Master/Utils/URLs.swift
> +    static let searchRecipes = "https://api.spoonacular.com/recipes/search?"
```suggestion
    static let randomRecipes = "https://api.spoonacular.com/recipes/random"
    static let product = "https://api.spoonacular.com/food/products/search"
    static let searchRecipes = "https://api.spoonacular.com/recipes/search"
```

2020-06-17 03:16 UTC, anhnv-0990 requested changes

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Data/Product/DetailProduct/Nutrition.swift
> +    var percentCarbs: Double = 0.0
tách ra file riêng

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Data/Product/Product.swift
> +    var imageType: String = ""
như trên

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Data/Source/API/Error/ErrorResponse.swift
> +
xoá dòng thừa

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Data/Source/API/SearchRequest.swift
> +         "apiKey": ApiKey.apiKey
coding convention

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Data/Source/API/SearchRequest.swift
> +    }
request sao lại có map?

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Repositories/Repositories.swift
> +        guard let input = SearchRequest(query: query, number: number) else { return }
guard let chỗ này làm gì đây em?

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Repositories/Repositories.swift
> +        guard let input = SearchRequest(number: number) else { return }
như trên

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Scenes/Main/HeaderCell/HomeHeaderView.swift
> +class HomeHeaderView: UITableViewHeaderFooterView {
final

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Scenes/Main/HomeTableViewCell/HomeTableViewCell.swift
> +class HomeTableViewCell: UITableViewCell {
bỏ import nếu k dùng
final

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Utils/Constant.swift
> +    static let heightOfHeaderInSection = CGFloat(45)
`static let heightOfHeaderInSection: CGFloat = 45 `

2020-06-17 03:16 UTC, anhnv-0990 commented on Spoon Master/Utils/URLs.swift
> +    static let searchRecipes = "https://api.spoonacular.com/recipes/search?"
tạo 1 base url rồi những cái dưới cộng thêm phần phía sau

2020-06-17 07:41 UTC, datdt-1935 commented on Spoon Master/Repositories/Repositories.swift
> +        api.request(input: input!, completion: { (object: Product?, error) in
không force unwrap

2020-06-17 07:41 UTC, datdt-1935 commented on Spoon Master/Repositories/Repositories.swift
> +        api.request(input: input, completion: { (object: RandomRecipes?, error) in
```suggestion
        api.request(input: input) { (object: RandomRecipes?, error) in
```

2020-06-18 02:29 UTC, datdt-1935 approved these changes

2020-06-18 02:30 UTC, merged